package gomez_tp7;

import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author jon gomez
 */
public class vistaFormularioDeInscripcion extends javax.swing.JInternalFrame {

    private HashSet<Alumno> alum = new HashSet<>();
    private HashSet<Materia> mat = new HashSet<>();
    
    public vistaFormularioDeInscripcion(HashSet<Alumno> alum, HashSet<Materia> mat) {
        initComponents();
        this.alum = alum;
        this.mat = mat;
        llenarComboAlumno();
        llenarComboMateria();
        comprobarCombos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInscribir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboMateria = new javax.swing.JComboBox<>();
        comboAlumno = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(204, 204, 102));
        setClosable(true);
        setPreferredSize(new java.awt.Dimension(460, 360));

        btnInscribir.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnInscribir.setText("Inscribir");
        btnInscribir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInscribir.setEnabled(false);
        btnInscribir.setPreferredSize(new java.awt.Dimension(71, 30));
        btnInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscribirActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel4.setText("Formulario de inscripción");

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Alumno:");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Materia:");

        comboMateria.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        comboMateria.setSelectedIndex(-1);
        comboMateria.setToolTipText("Seleccione a la materia");

        comboAlumno.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        comboAlumno.setSelectedIndex(-1);
        comboAlumno.setToolTipText("Seleccione al alumno");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel4))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(comboAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(comboMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(btnInscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(comboAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(comboMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(btnInscribir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscribirActionPerformed
        // TODO add your handling code here:
        try{
        Alumno a = (Alumno)comboAlumno.getSelectedItem();
        Materia m = (Materia)comboMateria.getSelectedItem();
        
        if(!a.getMaterias().contains(m)){
            a.agregarMateria(m);
            JOptionPane.showMessageDialog(this, "El alumno " + a.getNombre() + ", " + a.getApellido() + " ha sido inscripto en " + m.getNombre() + " del año " + m.getAnio());
        }
        else{
            JOptionPane.showMessageDialog(this, "No se pudo inscribir al alumno");
            comboAlumno.setSelectedIndex(-1);
            comboMateria.setSelectedIndex(-1);
        }
        }catch(NullPointerException np){
            JOptionPane.showMessageDialog(this, "Seleccione un alumno y una materia para continuar");
        }
    }//GEN-LAST:event_btnInscribirActionPerformed

    private void llenarComboAlumno(){
        for(Alumno a : alum){
            comboAlumno.addItem(a);
        }
    }
    
    private void llenarComboMateria(){
        for(Materia m : mat){
            comboMateria.addItem(m);
        }
    }
    
    private void comprobarCombos(){
        if(comboAlumno.getItemCount() > 0 && comboMateria.getItemCount() > 0){
            btnInscribir.setEnabled(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInscribir;
    private javax.swing.JComboBox<Alumno> comboAlumno;
    private javax.swing.JComboBox<Materia> comboMateria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
